### ISSUE TITLE
curious, if i have multiple lesser than 2^60 values greater than can be fit into the array, how to split into multiple arrays?

### ISSUE THREAD

**Issue by hiqsociety** [jwilder/encoding#10]
curious, if i have multiple lesser than 2^60 values greater than can be fit into the array, how to split into multiple arrays?

coz encodeall will break out of this. so how do u do more values than can be packed into simple8b? what's the function for it? how to have multiple simple8b arrays of array?

**Comment by jwilder** [comment]
I don’t fully understand the question.  Simple8b encoding packs multiple small integers into a uint64.  If there are more values than can fit into a uint64, they get encoded into a new uint64 and appended to the set. This repeats until all the values are encoded.  

This kind of encoding is useful if you have arrays of relatively small integers where many of the bits for the data type are wasted space.
