### ISSUE TITLE
Recent commit appears to have broken all old influxdb releases

### ISSUE THREAD

**Issue by jeremytho** [jwilder/encoding#5]
Commit id 716337b3fcfcb524274d8f7e07ed50aaa7d432cc seems to have caused compile failures on all old versions of influxdb. Influxdb directly references this github repo in its source with no versioning whatsoever. It's been fixed in master to reflect this change, but versions 0.12 and all previous releases using this library appear to be broken.

I think this suggests a good motivation to manage this lib with branches/tags/releases.

**Comment by jwilder** [comment]
Influxdb manages dependencies with gdm starting in 0.11. See https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md

**Comment by jeremytho** [comment]
Apologies as I know this probably isn't the right place to ask this, and I'm not at all familiar with go - I'm just wondering, doesn't this style of import behavior (this is from the 0.11 branch) directly ref this library?

import (
	"encoding/binary"
	"fmt"

	"github.com/jwilder/encoding/simple8b"
)

**Comment by jwilder** [comment]
Go uses the libraries currently checked out in your GOPATH. gdm uses the commit referenced in the Godeps file in the root of the project and switches to that version when restoring dependencies.  There are several tools like this for go as well as vendoring in newer versions of Go.

**Comment by jeremytho** [comment]
Thank you. I can see what you mean now in the Godeps file, I might just have to fiddle with Gopath in my build chain. Apologies again for the distraction on your library - I'm going to close this issue. Appreciate the insight.
